2024 67 new sensors
flipoyo/MOLONARI1D pull request #160
Opened 2024-11-21 09:41 UTC by alicehyf

field data uploaded and documentation for calibration

2024-11-21 09:56 UTC, flipoyo requested changes
1. please merge the main branch into your branch and resend the PR (the structur of the doc has changed).

2. Files are missing for the data.
2.1 For each point a Point<id>_info.csv file is mandatory
2.2 You should also provide a Notice<id>.txt file that stated where the sample comes from and when the measurments were performed
2.3 For each pressure sensor, you must add a calibration file in Laboratory/pressure_sensors/P<id_sensor>.csv --> please contact your advisors with me in CC if you need further assistance with that.
2.4 same for temperature sensors, ask for assistance if needed as for 2.3

2024-11-28 20:45 UTC, alicehyf commented
We have uploaded the point infos and the notice. However we don't have the exact callibration laws for the temperature sensors (cf. Agnes email), so we could not create that. Please check our work.

2024-11-29 16:11 UTC, flipoyo approved these changes

2024-11-29 16:11 UTC, merged

2024-11-29 16:28 UTC, flipoyo commented
please verify IPT in the svg files of point2024-1 and 2